config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get 'home/index'
  resources :groups, only: [:index, :show, :new, :create, :destroy] do
    resources :purchases, only: [:new, :create, :destroy]
  end
end
#  EDITOR="mate --wait" bin/rails credentials:edit

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    return unless user.present?

    # Define abilities for the user here. For example:
    can :manage, Group, author_id: user.id
    can :manage, Purchase, author_id: user.id

    # return unless user.is? :admin

    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :purchases, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :icon, presence: true
end

app/models/group_purchases.rb
class GroupPurchase < ApplicationRecord
  belongs_to :group
  belongs_to :purchase
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups, dependent: :destroy
  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, foreign_key: :author_id, dependent: :destroy
  has_many :purchases, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :email, presence: true, length: { minimum: 2, maximum: 50 }
  validates :password, presence: true, length: { minimum: 6, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |user_params| user_params.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:name, :email, :password)
    end
  end

  def after_sign_in_path_for(_resource)
    groups_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all.where(author: current_user)
  end

  def show
    @group = Group.find(params[:id])
    @purchases = @group.purchases.order('created_at DESC')
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render 'new'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def new
    @user = current_user
    @purchase = Purchase.new

    @group = Group.find_by(id: params[:group_id])
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @group = Group.find_by(id: params[:group_id])
    @group.purchases << @purchase

    if @purchase.save
      flash[:success] = 'purchase saved successfully'
      redirect_to group_path(@group)

    else
      flash[:error] = "Invalid input, purchase didn't get saved"
      render :new
    end
  end

  def destroy
    @purchase = Purchase.find(params[:id])
    @purchase.destroy

    redirect_to groups_path
  end

  private

  def purchase_params
    params.require(:purchase).permit(:name, :amount, :author_id).merge(author_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/groups/_group.html.erb
<li class="d-flex flex-row justify-content-between align-items-center card- mt-2">
    <%= image_tag group.icon, class: "img-icon" %>
    <P class="group-det"><%= group.name %></p>
    <P class="me-3">Total: $<%= group.purchases.map{|s| s.amount}.sum %></p>
</li>

app/views/groups/index.html.erb
<div class="group-nav d-flex flex-row justify-content-between">
 <%= link_to  groups_path, class: "link-add-cat ps-2" do %>
    <i class="fa-sharp fa-solid fa-arrow-left top-link"></i>
  <% end %>
  <h3 class="nav-add-tras">TRANSACTIONS</h3>
  <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "link-add-cat ps-2 top-link" do %>
     <i class="fa-solid fa-arrow-right-from-bracket pe-2"></i>
  <% end %>
</div><br/>
    <lu class="d-flex flex-column container-fluid">
      <% @groups.each do |group| %>
      <%= link_to group_path(group), class: "link-" do %>
        <%= render "group", group: group%>
        <% end %>
      <% end %>
    </lu>
    <br/>
<div class="container-fluid">
  <div class="d-flex justify-content-center  btn-p">
    <%= link_to "Add Item", new_group_path, class: "btn-prima" %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="add-cat-nav">
 <%= link_to  groups_path, class: "link-add-cat ps-2" do %>
    <i class="fa-sharp fa-solid fa-arrow-left top-link"></i>
  <% end %>
  <h3 class="nav-add-cat">ADD CATEGORY</h3>
</div>

<%= form_with model: @group, url: groups_path, class: "new-category container-fluid" do |form| %>
  <div>
    <% if @group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-field">
  <br/>
    <%= form.text_field :name, placeholder: "Category name", class: "form-control"%>
  </div>
  <br/>
  <div class="form-field">
    <%= form.text_field :icon, placeholder: "Link for icon", class: "form-control" %>
  </div>
  </div>
  <br/>

  <div class="d-flex justify-content-center btn-p btn-b mb-5">
    <%= form.submit "Save", class: "btn-prima ps-5 pe-5" %>
  </div>

<% end %>

app/views/groups/show.html.erb
<div class="add-cat-nav">
 <%= link_to  groups_path, class: "link-add-cat ps-2" do %>
    <i class="fa-sharp fa-solid fa-arrow-left top-link"></i>
  <% end %>
  <h3 class="nav-add-cat">DETAILS</h3>
</div>

<div class="container-fluid">
  <%= render "group", group: @group%>

  <div class="container-fluid">
  <ul style="list-item-style:none; margin-left:0px;padding-left:0px;">
    <%@purchases.each do |purchases|%>
    <li class= "category-item d-flex flex-row justify-content-between align-items-center p-2 mt-3 card-">
      <p class="ps-2"><%= purchases.name %></p>
      <p class="pe-2">$<%= purchases.amount %></p>
    </li>
    <%end%>
  </ul>
  <div class="d-flex justify-content-center btn-p">
    <%= link_to "New Purchase", new_group_purchase_path(@group), class: "btn-prima" %>
  </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="home-page">
  <h2 class="app-name">Budget App</h2>
  <div class="hom container-fluid mb-3">
    <div class="prim">
      <%= link_to "LOG IN", new_user_session_path, class: "home-log"%>
    </div>
    <div class="prima">
      <%= link_to "SIGN UP", new_user_registration_path, class: "home-sign" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    
  </head>

  <body>
    <% if notice %>
      <%= render 'shared/alerts' %>
    <% end %>
    <% if alert %>
      <%= render 'shared/popup' %>
    <% end %>
    <div class="">
      <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/3bb9b809c5.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/purchases/new.html.erb
<div class="add-cat-nav">
 <%= link_to  group_path(@group), class: "link-add-cat ps-2" do %>
    <i class="fa-sharp fa-solid fa-arrow-left top-link"></i>
  <% end %>
  <h3 class="nav-add-cat">ADD TRANSACTION</h3>
</div>


<%= form_with model: @purchase, url: group_purchases_path(@group) , local: true do |f| %>

<div class="container-fluid">
  <div class="field form-group">
    <br>
    <%= f.text_field :name, :required => true, placeholder: "Name", class: "form-control" %>
  </div>

  <div class="field form-group"></br>
    <%= f.text_field :amount, :required => true, placeholder: "Amount", class: "form-control" %>
  </div>
  </br>
  <div class="form-group">
    <%= select_tag :group, options_from_collection_for_select(Group.all, :id, :name, params["group_id"]), class: "form-con" %>
  </div>
  </br>
  <div class="d-flex justify-content-center btn-p btn-b mb-5">
    <%= f.submit "Create Purchase", class: "btn-prima ps-5 pe-5" %>
  </div>
</div>

<% end %>

app/views/shared/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
</div>

app/views/shared/_popup.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
</div>